#!/bin/bash
   echo -e "\033[1;35m\033[1m\033[4m" # Enable ANSI escape codes
prompt="||gitstat||>>>"
tpmorp="<<<<<<<<<<<<<<<<<<<<<<<"
   
n() {
	echo "" 
}

BASHRC_FILE="$HOME/.bashrc"
WHICHGIT=$(which git)
GIT=$WHICHGIT
GIT_ALIAS=$(perl -nle 'print $1 if /^\s*[^#]/ && /alias\s+git=\s*['"'"'"]?(.+?)['"'"'"]?\s*$/' $BASHRC_FILE)

#Display current system git executable
n
echo "$prompt Git system: $WHICHGIT"
echo "$prompt Git alias: $GIT_ALIAS"
echo -e "\033[0m"
if [ -n "$GIT_ALIAS" ]; then
	       WHICHGIT="$(which $GIT_ALIAS)"
	       GIT=$GIT_ALIAS
   echo "$prompt Using Git executable: $WHICHGIT"
else
   echo "$prompt Warining: Git alias not found in $BASHRC_FILE" >&2
fi	

# Display current repository status
n
echo "$prompt Repository Status: $tpmorp"
$GIT status


# Display local and remote branches
n
echo "$prompt Branches: $tpmorp"
$GIT branch -a
n

# Display remotes
n
echo "$prompt Remotes: $tpmorp"
$GIT remote -v
n


# Display current credentials
n
echo "$prompt Credentials: $tpmorp"
$GIT config --list | grep -E "user.name|user.email|credential.helper"
n
echo "$prompt Good luck!"
n


